# Use Alpine as the base image
FROM alpine:latest

# Set environment variables
ENV NVIM_LISTEN_ADDRESS=0.0.0.0:6666

# Install dependencies and Neovim
RUN apk update && apk add --no-cache \
    neovim \
    bash \
    curl \
    git \
    pv \
    && rm -rf /var/cache/apk/*

COPY nvim_deps.tar /nvim.tar
RUN tar -xvf /nvim.tar
# Expose the port for Neovim to listen on
EXPOSE 6666
RUN adduser -S nvim_user
USER nvim_user
#RUN git clone --depth 1 https://github.com/wbthomason/packer.nvim\
# ~/.local/share/nvim/site/pack/packer/start/packer.nvim

RUN /nvim_deps/install_nvim.sh
# Start Neovim in headless mode listening on the specified address
CMD ["nvim", "--headless", "--listen", "0.0.0.0:6666"]

