# Use Alpine as the base image
FROM alpine:latest

# Set environment variables
ENV NVIM_LISTEN_ADDRESS=0.0.0.0:6666

# Install dependencies and Neovim
RUN apk update && apk add --no-cache \
    neovim \
    bash \
    curl \
    && rm -rf /var/cache/apk/*

# Expose the port for Neovim to listen on
EXPOSE 6666
ENTRYPOINT [ "/bin/bash" ]
# Start Neovim in headless mode listening on the specified address
